name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Clean build directory
            run: rm -rf build
          - name: Run unit test
            run: ./unit-test.sh
            env:
              PATH: /usr/bin:/bin:/usr/local/bin
              CC: /usr/bin/gcc
              CXX: /usr/bin/g++
              LD: /usr/bin/ld
            
    full-test:
        runs-on: self-hosted
        needs: unit-test
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Clean build directory
            run: rm -rf build
          - name: Run full test
            run: ./full-test.sh
            env:
              PATH: /usr/bin:/bin:/usr/local/bin
              CC: /usr/bin/gcc
              CXX: /usr/bin/g++
              LD: /usr/bin/ld
